### ISSUE TITLE
Could not import packages for CMIknn and GPDC estimation

### ISSUE THREAD

**Issue by yubaocheng258** [jakobrunge/tigramite#66] opened 2020-06-06 09:41 UTC
Hello!Now I have a question need your help: I have already installed   tigramite-master(new) and all packages it needs. But when I used Geany to run the example in documents, it still display an error "Could not import packages for CMIknn and GPDC estimation", I wonder whether I have loss some packages I don't know. Please tell me the truth. Thank you very much

**Comment by jakobrunge** [comment] 2020-06-06 12:33
It means that you didn't follow the installation instructions:
python setup.py install
This will install tigramite in your path.
To use just the ParCorr and CMIsymb independence tests, only numpy and scipy are required. For other independence tests more packages are required:
CMIknn: cython can optionally be used for compilation, otherwise the provided ``*.c'' file is used
GPDC: also based on cython, and additionally, scikit-learn is required for Gaussian Process regression
RCOT requires more work: Firstly, rpy2 is required to access R-packages. The required R-packages can be installed with the script ``install_r_packages.sh''. Due to R-related issues, the installation of R's devtools might fail when running "install_r_packages.sh". This can be solved e.g. by installing missing / not resolved R dependencies using conda: "conda install r-git2r".

RCOT will not be in future releases to avoid R-dependencies.

**Comment by yubaocheng258** [comment] 2020-06-06 14:00
> It means that you didn't follow the installation instructions:
> python setup.py install
> This will install tigramite in your path.
> To use just the ParCorr and CMIsymb independence tests, only numpy and scipy are required. For other independence tests more packages are required:
> CMIknn: cython can optionally be used for compilation, otherwise the provided *.c'' file is used GPDC: also based on cython, and additionally, scikit-learn is required for Gaussian Process regression RCOT requires more work: Firstly, rpy2 is required to access R-packages. The required R-packages can be installed with the script install_r_packages.sh''. Due to R-related issues, the installation of R's devtools might fail when running "install_r_packages.sh". This can be solved e.g. by installing missing / not resolved R dependencies using conda: "conda install r-git2r".
> RCOT will not be in future releases to avoid R-dependencies.

Thank you for your reply, I will try it

**Comment by yubaocheng258** [comment] 2020-06-07 01:22
> It means that you didn't follow the installation instructions:
> python setup.py install
> This will install tigramite in your path.
> To use just the ParCorr and CMIsymb independence tests, only numpy and scipy are required. For other independence tests more packages are required:
> CMIknn: cython can optionally be used for compilation, otherwise the provided *.c'' file is used GPDC: also based on cython, and additionally, scikit-learn is required for Gaussian Process regression RCOT requires more work: Firstly, rpy2 is required to access R-packages. The required R-packages can be installed with the script install_r_packages.sh''. Due to R-related issues, the installation of R's devtools might fail when running "install_r_packages.sh". This can be solved e.g. by installing missing / not resolved R dependencies using conda: "conda install r-git2r".
> RCOT will not be in future releases to avoid R-dependencies.

Sorry, I have already test all packages : include numpy, scipy, scikit-learn,matplotlib,networkx,cython,mpi4py,rpy2,r-git2r and RCIT,but it still display "Could not import packages for CMIknn and GPDC estimation". What should I do?

**Comment by yubaocheng258** [comment] 2020-06-07 09:37
![picture](https://user-images.githubusercontent.com/66513596/83965283-2336ea00-a8e5-11ea-92b8-53bebbc28a8c.png)
Further more ,If I used cmd to run the example,it will diaplay the error like the picture ,I also install the tigramite-developer, I wonder what's worng with that. I'm looking forward to your replay. Thank you

**Comment by jakobrunge** [comment] 2020-06-07 12:05
Sorry, that was a typo, use pcmci.print_significant_links(...) instead (without the prefix "_"). 
It's fixed in the developer now....

**Comment by yubaocheng258** [comment] 2020-06-07 12:30
Thank you for your reply.The problem solved.Thank you very much!!!!

**Closed as completed** 2020-06-07 12:39 UTC
